### ISSUE TITLE
Sometimes present methods

### ISSUE THREAD

**Issue by dvnstrcklnd** [klavinslab/aq-thermocyclers#1]
Thermocyclers has a block of code with
`if thermocycler.respond_to?(:set_dye)`
this is a type check.  Just like with inheritance, it is better to have a method that executes this block in the classes that have the set_dye method but does nothing in those that don’t

**Comment by dvnstrcklnd** [comment]
@bjkeller Would this new method be in the Thermocyclers module?

**Comment by bjkeller** [comment]
I'd guess AbstractThermocyclers

**Comment by dvnstrcklnd** [comment]
The reason I am not pushing it there is that `show` methods don't work from inside classes. The `ThermocyclerHelper` module is intended to be a layer between the protocol and the thermocycler that handles this logic.

**Comment by bjkeller** [comment]
in general, you should avoid code that says "if the thing has this type, then do behavior" and use polymorphism be it through inheritance or duck typing to ensure this behavior is somehow bound to the definition of the type.

I don't have a definitive answer for you when the behavior is presentation, but given the prevalence of MVC I'm sure it is out there.  I can look later if needed.  (It is probably going to look like a variant of the factory pattern for the PCR program)

(BTW It is possible to pass the protocol and use the show block on that object)

**Comment by dvnstrcklnd** [comment]
OK, I understand. What I think I've realized here is that I am subtly overloading the thermocycler object. Whether the thermocycler is qPCR-capable is not the same as whether I want to do a qPCR experiment.

**Comment by dvnstrcklnd** [comment]
If I want to do a qPCR experiment, but the thermocycler is not qPCR capable, then it should raise an exception. This is terrible code!

**Comment by dvnstrcklnd** [comment]
Could you define a pattern for passing the protocol? IIRC, the show stealer thing that Eric came up with wasn't very reliable.
